apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "nginx-ingress-exporter.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}    
  name: {{ template "nginx-ingress-exporter.fullname" . }}
spec:
  selector:
    matchLabels:
      component: controller
  namespaceSelector:
    matchNames:
      - {{ .Values.namespaceSelector }}
  endpoints:
  - port: metrics
    interval: 15s
    #bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
