{
 "title": "Kubernetes Cluster Overview",
 "description": "Kubernetes Cluster Overview",
 "tags": [
  "overview",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts Firing",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
      }
     ]
    },
    {
     "title": "Node Not Ready",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes Unschedulable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    },
    {
     "title": "Node Memory Pressure",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "Node Disk Pressure",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "Running Pod",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sum(kubelet_running_pod_count)" }
     ]
    },
    {
     "title": "Running Container",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kubelet_running_container_count)"
      }
     ]
    },
    {
     "title": "Node: $node",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
     "repeat": "node",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kubelet_running_pod_count{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Node: $node",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
     "repeat": "node",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kubelet_running_container_count{instance=~\"$node\"}"
      }
     ]
    }
   ]
  },
  { "title": "Cluster Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Cluster CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[5m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity_memory_bytes)"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_container_info)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "All Nodes Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Number of Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_uname_info)" }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"user\"})"
    }
   ]
  },
  {
   "title": "Used Memery",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes)"
    }
   ]
  },
  {
   "title": "Total Memery",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "DIsk Usage(Local)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)"
    }
   ]
  },
  {
   "title": "DIsk Total(Local)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Avg CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (avg by (cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Avg Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Network Usage(RX/TX)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (rate(node_network_receive_bytes_total{device=~\"eth0|ens32\"}[5m])))",
     "legendFormat": "Inbound: {{ instance }} "
    },
    {
     "expr": "(sum by (instance) (rate(node_network_transmit_bytes_total{device=~\"eth0|ens32\"}[5m])))",
     "legendFormat": "Outbound: {{ instance }}"
    }
   ]
  },
  {
   "title": "Avg Disk Usage(Local)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)) / sum(node_filesystem_size_bytes)) * 100"
    }
   ]
  }
 ]
}