{
 "title": "Kubernetes Kubelet Performance",
 "description": "Used to view and monitor Kubernetes performance.\r\n\r\nSee also https://github.com/cofyc/k8s-testing.",
 "tags": [
  "kubernetes",
  "kubelet"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "percentile", "query": "0.1,0.25,0.5,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Kubelet Pod Start Latency",
   "type": "graph",
   "description": "Latency in microseconds for a single pod to go from pending to running. Broken down by podname.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_pod_start_latency_microseconds_sum[5m]) / rate(kubelet_pod_start_latency_microseconds_count[5m])",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "Storage Operation Duration - $percentile Quantile",
   "type": "graph",
   "description": "Storage operation duration.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(storage_operation_duration_seconds_bucket[2m])) by (le, volume_plugin, operation_name))",
     "legendFormat": "{{volume_plugin}} - {{operation_name}}"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "kubelet - {{instance}}" }
   ]
  },
  {
   "title": "Creating Rate of Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_running_pod_count[2m]))",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_container_count",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "Creating Rate of Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_running_container_count[2m])",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "Kubelet CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kubelet\"}[2m])",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  }
 ]
}