{
 "title": "Zookeerper Overview",
 "description": "Zookeerper Exporter Overview",
 "tags": [
  "zookeeper",
  "Prometheus",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(zk_up,instance)" },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Znodes/watches count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_znode_count{instance=\"$instance\"}",
     "legendFormat": "zk_znode_count"
    },
    {
     "expr": "zk_watch_count{instance=\"$instance\"}",
     "legendFormat": "zk_watch_count"
    }
   ]
  },
  {
   "title": "活跃连接数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zk_num_alive_connections{instance=\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "zk_num_alive_connections"
    }
   ]
  },
  {
   "title": "数据总和大小",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zk_approximate_data_size{instance=\"$instance\"}",
     "legendFormat": "zk_approximate_data_size"
    }
   ]
  },
  {
   "title": "收发包/秒",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(zk_packets_sent{instance=\"$instance\"}[$interval]) or rate(zk_packets_sent{instance=\"$instance\"}[5m])",
     "legendFormat": "zk_packets_sent"
    },
    {
     "expr": "irate(zk_packets_received{instance=\"$instance\"}[$interval]) or rate(zk_packets_received{instance=\"$instance\"}[5m])",
     "legendFormat": "zk_packets_received"
    }
   ]
  },
  {
   "title": "响应延迟",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zk_max_latency{instance=\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "zk_max_latency"
    },
    {
     "expr": "sum(rate(zk_min_latency{instance=\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "zk_min_latency"
    },
    {
     "expr": "sum(rate(zk_avg_latency{instance=\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "zk_avg_latency"
    }
   ]
  }
 ]
}