apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prometheus
    prometheus: k8s
    release: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-k8s
