apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "ceph-exporter.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: {{ .Values.serviceMonitor.releaseLabel }}
    prometheus: {{ .Release.Name }}
    {{- if .Values.serviceMonitor.additionalServiceMonitorLabels }}
{{ toYaml .Values.serviceMonitor.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}    
  name: {{ template "ceph-exporter.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "ceph-exporter.name" . }}
      release: "{{ .Release.Name }}"
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
  - port: {{ .Values.serviceMonitor.scheme }}-metrics
    interval: 30s
