# where the mysql installed namespace
namespaceSelector: prod
# endports
endpoints: []
# on what port are the metrics exposed by redis
metricsPortName: metrics
metricsPort: 9121
# Are we talking http or https?
scheme: http
# default rules are in templates/redis-servicemonitor.rules.yaml
# prometheusRules: {}
## Custom Labels to be added to ServiceMonitor
# 经过测试，servicemonitor标签添加prometheus operator的release标签即可正常监控
additionalServiceMonitorLabels: 
  release: prometheus-operator
##Custom Labels to be added to Prometheus Rules CRD
additionalRulesLabels: 
  release: prometheus-operator
