apiVersion: v1
kind: Service
metadata:
  name: {{ template "node-exporter-servicemonitor.fullname" . }}
  labels:
    app: {{ template "node-exporter-servicemonitor.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
      protocol: TCP
      name: {{ .Values.metricsPortName }}
