apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-router
  namespace: monitoring
  labels:
    k8s-app: kube-router
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http-metrics
    interval: 30s
  selector:
    matchLabels:
      k8s-app: kube-router
  namespaceSelector:
    matchNames:
    - kube-system
