apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper-servicemonitor.fullname" . }}
  labels:
    app: {{ template "zookeeper-servicemonitor.name" . }}
    chart: {{ template "zookeeper-servicemonitor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.namespaceSelector }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
      protocol: TCP
      name: "{{ .Values.metricsPortName }}"
  selector:
    app: zookeeper
    component: server
